spring:  
  profiles:
    active:
    - dev
    
---
spring:
  profiles: dev
  application:
    name: myconfig-dev
    
---
spring:
  profiles: test
  application:
    name: myconfig-test 
	

---
spring:
  profiles: test
  application:
    name: myconfig2

	