spring: 
  profiles:
    active: dev
---
server:
  port: 8888

spring:
  profiles: dev
  application:
    name: config-client
---
eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001:7001/eureka/