spring: 
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: config-client
	
---
eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001:7001/eureka/